# tap "homebrew/bundle"
# tap "homebrew/core"
# tap "wader/tap"
brew "act"
brew "fzf"
brew "gh"
brew "neovim"
brew "peco"
brew "python@3.11"
brew "pipenv"
brew "python@3.10"
brew "the_silver_searcher"
brew "tmux"
brew "vim"
brew "wader/tap/fq"
